export const BICYCLE_COLORS = [
  { name: "Matte Black", hex: "#1A1A1A" },
  { name: "Gloss Black", hex: "#000000" },
  { name: "Satin Black", hex: "#2C2C2C" },
  { name: "Charcoal Grey", hex: "#36454F" },
  { name: "Nardo Grey", hex: "#686A6C" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Titanium", hex: "#878681" },
  { name: "Gunmetal", hex: "#2a3439" },
  { name: "Pearl White", hex: "#F8F8FF" },
  { name: "Matte White", hex: "#FAFAFA" },
  { name: "Gloss White", hex: "#FFFFFF" },
  { name: "Ivory", hex: "#FFFFF0" },
  { name: "Racing Red", hex: "#FF0000" },
  { name: "Crimson", hex: "#DC143C" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Cherry Red", hex: "#990F02" },
  { name: "Neon Orange", hex: "#FF5F1F" },
  { name: "Burnt Orange", hex: "#CC5500" },
  { name: "Mango", hex: "#FDB813" },
  { name: "Mustard Yellow", hex: "#FFDB58" },
  { name: "Neon Yellow", hex: "#E8F48C" },
  { name: "Lime Green", hex: "#32CD32" },
  { name: "Olive Green", hex: "#556B2F" },
  { name: "Forest Green", hex: "#228B22" },
  { name: "Mint Green", hex: "#98FF98" },
  { name: "Teal", hex: "#008080" },
  { name: "Cyan", hex: "#00FFFF" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Electric Blue", hex: "#008FEF" }, // Primary Blue
  { name: "Navy Blue", hex: "#000080" },
  { name: "Midnight Blue", hex: "#191970" },
  { name: "Cobalt Blue", hex: "#0047AB" },
  { name: "Indigo", hex: "#4B0082" },
  { name: "Violet", hex: "#EE82EE" },
  { name: "Plum", hex: "#DDA0DD" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "Hot Pink", hex: "#FF69B4" },
  { name: "Rose Gold", hex: "#B76E79" },
  { name: "Copper", hex: "#B87333" },
  { name: "Bronze", hex: "#CD7F32" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Champagne", hex: "#F7E7CE" },
  { name: "Desert Sand", hex: "#EDC9AF" },
  { name: "Khaki", hex: "#C3B091" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "Coffee", hex: "#6F4E37" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Salmon", hex: "#FA8072" },
  { name: "Raw Carbon", hex: "#333333" }
];
